# Generated by Django 4.2.6 on 2023-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('mobilenumder', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
